version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers
    steps:
      - checkout
      - run: sudo composer --version
      - run: 
          name: Install Composer
          command: composer install -n --prefer-dist
          working_directory: src
      - run: 
          name: npm CI
          command: npm ci
          working_directory: src
      - run: 
          name: npm run dev
          command: npm run dev
          working_directory: src