version: 2.1

commands:
  npm-ci:
    steps:
      - run:
          name: npm CI
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi
          working_directory: src
  restore-cache-npm:
    steps:
      - restore_cache:
          key: npm-v1.1-{{ checksum "src/package-lock.json" }}
  save-cache-npm:
    steps:
      - save_cache:
          key: npm-v1.1-{{ checksum "src/package-lock.json" }}
          paths:
            - src/node_modules

jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers
    steps:
      - checkout
      - run: sudo composer --version
      - restore_cache:
          key: composer-v1.1-{{ checksum "src/composer.lock" }}
      - run: 
          name: Install Composer
          command: composer install -n --prefer-dist
          working_directory: src
      - save_cache:
          key: composer-v1.1-{{ checksum "src/composer.lock" }}
          paths:
            - src/vendor
      - restore-cache-npm
      - npm-ci
      - save-cache-npm
      - run: 
          name: npm run dev
          command: npm run dev
          working_directory: src
  deploy:
    docker: 
      - image: circleci/php:7.4-node-browsers
    environment:
      AWS_DEFAULT_REGION: ap-northeast-1
    steps:
      - checkout
      - restore_cache:
          key: composer-no-dev-v1-{{ checksum "src/composer.lock" }}
      - run: 
        name: Install Composer --no-dev
        command: composer install -n --no-dev --prefer-dist
        working_directory: src
      - save_cache:
          key: composer-no-dev-v1-{{ checksum "src/composer.lock" }}
          paths:
            - src/vendor
      - restore-cache-npm
      - npm-ci
      - save-cache-npm
      - run:
        command: npm run prod
        working_directory: src
      - run:
          name: archive artifacts
          command: zip -ryq funnde-src.zip ./src
          working_directory: src
      - aws-cli/install
      - run:
          name: upload artifacts to s3
          command: aws s3 cp funnde-src.zip s3://${AWS_S3_BUCKET_NAME}
          working_directory: src
      - run:
          name: deploy to prod
          command: |
            aws deploy create-deployment \
            --application-name funnde \
            --deployment-group-name funnde \
            --s3-location bucket=${AWS_S3_BUCKET_NAME},key=funnde-src.zip,bundleType=zip
          working_directory: src

orbs:
  aws-cli: circleci/aws-cli@1.0.0

workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main
                